SELECT M.ID, M.NAME, D.NAME as "Disk Name", D.DISK_SIZE, D.DISK_USED, D.DISK_FREE
FROM ORG1.MACHINE M
JOIN MACHINE_DISKS D on M.ID = D.ID
LEFT JOIN DELL_ASSET DA on M.BIOS_SERIAL_NUMBER = DA.SERVICE_TAG
WHERE DISK_FREE < 10 
AND (D.NAME like "Drive C:%" 
OR D.NAME like "Macintosh HD%")