SELECT MACHINE.NAME AS SYSTEM_NAME, 
MACHINE.OS_NAME, MACHINE.LAST_SYNC,
LOCATION.NAME as "Location",
GROUP_CONCAT(DISTINCT SOFTWARE.DISPLAY_NAME SEPARATOR '\n') AS SOFTWARE_DISPLAY_NAME_GROUPED
FROM MACHINE  
LEFT JOIN MACHINE_SOFTWARE_JT ON (MACHINE_SOFTWARE_JT.MACHINE_ID = MACHINE.ID) 
LEFT JOIN SOFTWARE ON (SOFTWARE.ID = MACHINE_SOFTWARE_JT.SOFTWARE_ID) 
LEFT JOIN MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID)  
LEFT JOIN LABEL LOCATION ON (LOCATION.ID = MACHINE_LABEL_JT.LABEL_ID  AND LOCATION.TYPE <> 'hidden') 
LEFT JOIN LABEL_LABEL_JT ON (LOCATION.ID = LABEL_LABEL_JT.CHILD_LABEL_ID AND LABEL_LABEL_JT.LABEL_ID = 439)

WHERE MACHINE.OS_NAME like "Microsoft%"
and LABEL_LABEL_JT.LABEL_ID = 439
GROUP BY MACHINE.ID 
HAVING SOFTWARE_DISPLAY_NAME_GROUPED not like "%Microsoft Office Professional Plus 2013%"
ORDER BY SYSTEM_NAME