SELECT A.ID, M.NAME, A.NAME, A.LOCATION_ID, L.NAME as "Location",
M.LAST_INVENTORY, 
M.CS_MANUFACTURER, M.CS_MODEL,
M.OS_NAME
FROM ORG1.MACHINE M
JOIN ASSET A on A.MAPPED_ID = M.ID and A.ASSET_TYPE_ID = 5
JOIN ASSET_DATA_5 AD on AD.ID = A.ASSET_DATA_ID
JOIN ASSET L on L.ID = A.LOCATION_ID

WHERE A.LOCATION_ID = 12740
