SELECT MACHINE.NAME AS SYSTEM_NAME, 
USER_LOGGED, GROUP_CONCAT(SOFTWARE.DISPLAY_NAME) AS INSTALLEDSOFTWARE

FROM MACHINE  
LEFT JOIN MACHINE_SOFTWARE_JT ON (MACHINE_SOFTWARE_JT.MACHINE_ID = MACHINE.ID) 
LEFT JOIN SOFTWARE ON (SOFTWARE.ID = MACHINE_SOFTWARE_JT.SOFTWARE_ID) 
 
GROUP BY MACHINE.ID 
HAVING INSTALLEDSOFTWARE like '%KB3124275%' and INSTALLEDSOFTWARE like '%KB3104002%'

ORDER BY SYSTEM_NAME
LIMIT 100