SELECT MACHINE.NAME AS SYSTEM_NAME, 
SYSTEM_DESCRIPTION, 
MACHINE.IP, 
MACHINE.MAC, 
MACHINE.ID as TOPIC_ID,
left(UPTIME, locate(',', UPTIME) -1)
FROM MACHINE  
WHERE left(UPTIME, locate(',', UPTIME) -1) > 45