SELECT * FROM ORG1.ASSET_HISTORY 
WHERE
CHANGE_TYPE = "Detected"
and FIELD_NAME = "SOFTWARE"
and DATE(TIME) BETWEEN DATE_SUB(NOW(), INTERVAL 7 DAY) and  DATE(NOW())
and VALUE1 = "Google Chrome"
and VALUE2 = '48.0.2564.103'