-- Our location asset contains a field for the support person for that building
-- This report shows computers with less than 10GB free 
-- and includes the location and the liaison
SELECT MACHINE.NAME,
LOCATION.NAME as "Building",
LIAISON.FULL_NAME as "Liaison",
D.NAME as "Disk Name", D.DISK_SIZE, D.DISK_USED, D.DISK_FREE
FROM MACHINE
JOIN MACHINE_DISKS D on MACHINE.ID = D.ID
JOIN ASSET on ASSET.MAPPED_ID = MACHINE.ID and ASSET.ASSET_TYPE_ID = 5
JOIN ASSET_DATA_5 ASSET_DATA on ASSET_DATA.ID = ASSET.ASSET_DATA_ID
JOIN ASSET LOCATION on LOCATION.ID = ASSET.LOCATION_ID and LOCATION.ASSET_TYPE_ID = 1
JOIN ASSET_DATA_1 LOCATION_DATA on LOCATION_DATA.ID = LOCATION.ASSET_DATA_ID
JOIN USER LIAISON on LIAISON.ID = LOCATION_DATA.FIELD_10021
JOIN MACHINE_LABEL_JT on MACHINE_ID = MACHINE.ID
JOIN LABEL on LABEL.ID = LABEL_ID
WHERE DISK_FREE < 10  and DISK_SIZE > 0
AND (D.NAME like "Drive C:%" OR D.NAME like "Drive / %")
AND LABEL.NAME = 'SL-In Department OU'