--Good example of the INET_ATON function
SELECT ID, NAME, MAC, IP, LAST_INVENTORY, OS_NAME, CS_MODEL FROM ORG1.MACHINE
WHERE INET_ATON(IP) between INET_ATON("172.16.96.1") and INET_ATON("172.16.103.255")
ORDER BY INET_ATON(IP);
