SELECT M.ID, M.NAME, M.LAST_INVENTORY, LAST_REBOOT, M.OS_NAME,
GROUP_CONCAT(DISTINCT SOFTWARE.DISPLAY_NAME SEPARATOR '\n') AS "Software Name",
GROUP_CONCAT(DISTINCT SOFTWARE.DISPLAY_VERSION SEPARATOR '\n') AS "Version",
(select PROCESS.NAME FROM PROCESS JOIN MACHINE_PROCESS_JT on MACHINE_PROCESS_JT.PROCESS_ID = PROCESS.ID WHERE PROCESS.NAME = "pc-client.exe" and MACHINE_PROCESS_JT.MACHINE_ID = M.ID) as PaperCutProcess,
(select PROCESS.NAME FROM PROCESS JOIN MACHINE_PROCESS_JT on MACHINE_PROCESS_JT.PROCESS_ID = PROCESS.ID WHERE PROCESS.NAME = "explorer.exe" and MACHINE_PROCESS_JT.MACHINE_ID = M.ID) as ExplorerProcess


FROM ORG1.MACHINE M
LEFT JOIN MACHINE_SOFTWARE_JT ON (MACHINE_SOFTWARE_JT.MACHINE_ID = M.ID) 
LEFT JOIN SOFTWARE ON (SOFTWARE.ID = MACHINE_SOFTWARE_JT.SOFTWARE_ID) 
WHERE (SOFTWARE.DISPLAY_NAME like 'PaperCut MF Client%')
and OS_NAME like "Mic%"
GROUP BY M.ID 
HAVING PaperCutProcess is null
and ExplorerProcess = "explorer.exe"
ORDER BY M.NAME