select NAME, IP, LAST_SYNC, UPTIME, KT.PHASE, CLIENT_CONNECTED
from MACHINE
join KBSYS.KONDUCTOR_TASK KT on KT.KUID = MACHINE.KUID and KT.TYPE like 'patch%' 
LEFT JOIN KBSYS.SMMP_CONNECTION ON SMMP_CONNECTION.KUID = MACHINE.KUID
WHERE KT.PHASE ='reboot pending'
order by MACHINE.NAME