SELECT T.TYPE, T.PHASE, MACHINE.NAME, K.CLIENT_CONNECTED, MACHINE.OS_NAME

FROM KBSYS.KONDUCTOR_TASK T
JOIN MACHINE on T.KUID = MACHINE.KUID
JOIN KBSYS.SMMP_CONNECTION K on K.KUID = MACHINE.KUID
WHERE PHASE = "deploying" and CLIENT_CONNECTED = 1;