--We had an issue with computers not runnning the PaperCut Client
--This report identifies computers that are connected to the KBox on campus that don't have the client runnning

select *, UNIX_TIMESTAMP(now()) - UNIX_TIMESTAMP(LAST_SYNC) as LAST_SYNC_TIME,
                       UNIX_TIMESTAMP(MACHINE.LAST_SYNC) as LAST_SYNC_SECONDS
                  from ORG1.MACHINE
                  LEFT JOIN KBSYS.KUID_ORGANIZATION ON KUID_ORGANIZATION.KUID=MACHINE.KUID
LEFT JOIN KBSYS.SMMP_CONNECTION ON SMMP_CONNECTION.KUID = MACHINE.KUID AND KUID_ORGANIZATION.ORGANIZATION_ID = 1
LEFT JOIN ORG1.MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID)
LEFT JOIN ORG1.LABEL ON (LABEL.ID = MACHINE_LABEL_JT.LABEL_ID  AND LABEL.TYPE <> 'hidden')
LEFT JOIN LABEL_LABEL_JT ON (LABEL.ID = LABEL_LABEL_JT.CHILD_LABEL_ID)
JOIN ORG1.MACHINE_PROCESS_JT on MACHINE_PROCESS_JT.MACHINE_ID = MACHINE.ID and MACHINE_PROCESS_JT.PROCESS_ID = 182321
JOIN ORG1.PROCESS on PROCESS.ID = MACHINE_PROCESS_JT.PROCESS_ID
WHERE LABEL_LABEL_JT.LABEL_ID = 258
and left(IP,7) = "172.16."
and CLIENT_CONNECTED = 1
