-- Report of computers that have a BIOS update available
-- Submitted as part of answer to https://www.itninja.com/question/leveraging-sql-info-to-script-bios-deployment

SELECT MACHINE_ID, MACHINE.NAME, APPLICABLE_UPDATE,
 DELL_PKG.NAME, DELL_PKG.DESCRIPTION
FROM ORG1.DELL_MACHINE_STATUS
JOIN KBSYS.DELL_PKG on DELL_PKG.PACKAGE_DID = DELL_MACHINE_STATUS.PACKAGE_DID
JOIN MACHINE on MACHINE.ID = DELL_MACHINE_STATUS.MACHINE_ID
WHERE DELL_PKG.COMPONENT_TYPE = "BIOS"
AND APPLICABLE_UPDATE = "UPGRADE"
;