SELECT M.ID, M.NAME, A.NAME, AD.FIELD_32 as PONumber, AD.FIELD_10013 as POCreated,
M.LAST_INVENTORY, 
M.CS_MANUFACTURER, M.CS_MODEL,
M.OS_NAME
FROM ORG1.MACHINE M
JOIN ASSET A on A.MAPPED_ID = M.ID
JOIN ASSET_DATA_5 AD on AD.ID = A.ASSET_DATA_ID

WHERE FIELD_10013 is null