SELECT NAME, MAC, IP, OS_NAME, OS_NUMBER,  
P.DATE_FIELD_VALUE as "Purchase Date",
SUBSTR(W.STR_FIELD_VALUE, LOCATE("WarrantyExpires", W.STR_FIELD_VALUE)+24, 10) as "Warranty Expires"

FROM ORG1.MACHINE
JOIN MACHINE_CUSTOM_INVENTORY W on W.ID = MACHINE.ID and W.SOFTWARE_ID = 59336
JOIN MACHINE_CUSTOM_INVENTORY P on P.ID = MACHINE.ID and P.SOFTWARE_ID = 25152

;