--This query uses the INET_ATON function as a trick to find software versions
SELECT MACHINE.NAME, SOFTWARE.DISPLAY_NAME, SOFTWARE.DISPLAY_VERSION
FROM MACHINE
JOIN MACHINE_SOFTWARE_JT on MACHINE_SOFTWARE_JT.MACHINE_ID = MACHINE.ID
JOIN SOFTWARE on MACHINE_SOFTWARE_JT.SOFTWARE_ID = SOFTWARE.ID and
DISPLAY_NAME like "Adobe Flash Player%"
and INET_ATON(DISPLAY_VERSION) < INET_ATON("21.0.0.213")
LEFT JOIN KBSYS.KUID_ORGANIZATION ON KUID_ORGANIZATION.KUID=MACHINE.KUID
LEFT JOIN KBSYS.SMMP_CONNECTION ON SMMP_CONNECTION.KUID = MACHINE.KUID AND KUID_ORGANIZATION.ORGANIZATION_ID = 1
WHERE CLIENT_CONNECTED = 1
ORDER BY MACHINE.NAME
