SELECT MACHINE.KUID,MACHINE.NAME AS SYSTEM_NAME,MACHINE.IP,MACHINE.MAC,MACHINE.OS_NAME,MACHINE.LAST_SYNC
FROM (MACHINE ,( select COUNT(ID) CT, MACHINE.MAC FROM MACHINE GROUP BY MACHINE.MAC )M2 ) 
WHERE M2.CT>1 and MACHINE.MAC=M2.MAC AND MACHINE.MAC != ""
ORDER BY MACHINE.MAC