SELECT ASSET_ID, ASSET_HISTORY.NAME, 
MACHINE.NAME, MACHINE.CS_MODEL, TIME, USER_TEXT, VALUE1, VALUE2 
FROM ORG1.ASSET_HISTORY 
JOIN MACHINE on MACHINE.BIOS_SERIAL_NUMBER = ASSET_HISTORY.NAME
WHERE FIELD_NAME = "OWNER_ID" ORDER BY TIME DESC