SELECT M.ID, M.NAME, LAB_LABEL.NAME, BUILDING_LABEL.NAME
FROM MACHINE M
JOIN MACHINE_LABEL_JT LABJOIN on LABJOIN.MACHINE_ID = M.ID
JOIN LABEL LAB_LABEL on LAB_LABEL.ID = LABJOIN.LABEL_ID 
JOIN LABEL_LABEL_JT LAB_BUILDING_JOIN on LAB_BUILDING_JOIN.CHILD_LABEL_ID = LAB_LABEL.ID
JOIN LABEL BUILDING_LABEL on BUILDING_LABEL.ID = LAB_BUILDING_JOIN.LABEL_ID
JOIN LABEL_LABEL_JT BUILDING_LABS_JOIN on BUILDING_LABS_JOIN.CHILD_LABEL_ID = BUILDING_LABEL.ID
WHERE BUILDING_LABS_JOIN.LABEL_ID = 271
