--We have labels to indicate the upgrade status of machines, e.g. bumpdown, deferred, etc.
--These labels are in a group
--Report shows computers with their upgrade status, if they don't have a label in the group then they are "In Cycle"
SELECT MACHINE.ID as UID, MACHINE.NAME,
CASE 
	WHEN USLABELS.UPGRADESTATUS is not null THEN USLABELS.UPGRADESTATUS
    ELSE "In Cycle"

END AS UPGRADESTATUS
FROM
MACHINE
LEFT JOIN (
SELECT M.ID, M.NAME, M.MAC, M.IP, M.OS_NAME, GROUP_CONCAT(LABEL.NAME) as UPGRADESTATUS
FROM MACHINE M
LEFT JOIN MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = M.ID)
LEFT JOIN LABEL ON (LABEL.ID = MACHINE_LABEL_JT.LABEL_ID  AND LABEL.TYPE <> 'hidden')
LEFT JOIN LABEL_LABEL_JT ON (LABEL_LABEL_JT.CHILD_LABEL_ID = LABEL.ID and LABEL_LABEL_JT.LABEL_ID = 1484)

WHERE LABEL_LABEL_JT.LABEL_ID = 1484

GROUP BY M.ID) AS USLABELS on USLABELS.ID = MACHINE.ID
ORDER BY MACHINE.NAME
