SELECT CAD.ID, COMPUTER.NAME, COMPUTER.MAPPED_ID, COMPUTER.ID, COMPUTER.LOCATION_ID, 
LOCATION.NAME, LOCATION.ASSET_CLASS_ID, LAD.PARENT
FROM ORG1.ASSET_DATA_5 CAD
JOIN ASSET COMPUTER on COMPUTER.ASSET_DATA_ID = CAD.ID and COMPUTER.ASSET_TYPE_ID = 5
JOIN ASSET LOCATION on LOCATION.ID = COMPUTER.LOCATION_ID
JOIN ASSET_DATA_1 LAD on LAD.ID = LOCATION.ASSET_DATA_ID
WHERE LOCATION.ASSET_CLASS_ID in (1,3)
AND COMPUTER.MAPPED_ID is not null
AND COMPUTER.MAPPED_ID != 0