SELECT M.NAME, M.OS_NAME, OWNER.USER_NAME as "UserName", OWNER.FULL_NAME as "Owner",
OWNERDESC.FIELD_VALUE as "Owner Desciption",
OWNERDEPT.FIELD_VALUE as "Owner Department",
OWNERTITLE.FIELD_VALUE as "Owner Title",
M.USER_FULLNAME as "Last User",
M.LAST_INVENTORY as "Last Inventory"
FROM MACHINE M
JOIN ASSET on ASSET.MAPPED_ID = M.ID
JOIN USER OWNER on OWNER.ID = ASSET.OWNER_ID

JOIN USER_FIELD_VALUE OWNERTITLE on OWNERTITLE.FIELD_ID = 1 AND OWNERTITLE.USER_ID = OWNER.ID
JOIN USER_FIELD_VALUE OWNERID on OWNERID.FIELD_ID = 2 AND OWNERID.USER_ID = OWNER.ID

JOIN USER_FIELD_VALUE OWNERDESC on OWNERDESC.FIELD_ID = 3 AND OWNERDESC.USER_ID = OWNER.ID
JOIN USER_FIELD_VALUE OWNERDEPT on OWNERDEPT.FIELD_ID = 4 AND OWNERDEPT.USER_ID = OWNER.ID

WHERE OWNER.USER_NAME not like '%computer'

ORDER BY M.NAME
