SELECT M.NAME, M.IP, M.LAST_SYNC, 
CASE 
    WHEN GROUP_CONCAT(SOFTWARE.DISPLAY_NAME) like "%Adobe Acrobat XI Pro%" THEN "Yes"
    WHEN GROUP_CONCAT(SOFTWARE.DISPLAY_NAME) not like "%Adobe Acrobat XI Pro%" THEN "No"

END AS "Acrobat Pro",
CASE
    WHEN GROUP_CONCAT(SOFTWARE.DISPLAY_NAME) like "%Photoshop%" THEN "Yes"
    WHEN GROUP_CONCAT(SOFTWARE.DISPLAY_NAME) not like "%Photoshop%" THEN "No"

END AS "Photoshop"
FROM ORG1.MACHINE M
JOIN MACHINE_SOFTWARE_JT on MACHINE_SOFTWARE_JT.MACHINE_ID = M.ID
LEFT JOIN SOFTWARE on SOFTWARE.ID = MACHINE_SOFTWARE_JT.SOFTWARE_ID
GROUP BY M.NAME