SELECT M.NAME, COUNT(P.ID), GROUP_CONCAT(P.TITLE) as "Not Patched"
FROM ORG1.PATCHLINK_MACHINE_STATUS PMS
JOIN KBSYS.PATCHLINK_PATCH P on P.UID = PMS.PATCHUID 
JOIN MACHINE M on M.ID = PMS.MACHINE_ID
JOIN ORG1.PATCHLINK_PATCH_STATUS PPS on PPS.PATCHUID = PMS.PATCHUID
WHERE PMS.STATUS = "NOTPATCHED"
and P.IS_SECURITY = 1
and P.IMPACTID = "Critical"
and PPS.STATUS = 0
GROUP BY M.NAME