SELECT MACHINE_ID, PMS.PATCHUID, PMS.STATUS, PMS.STATUS_DT, P.TITLE, P.IMPACTID, M.NAME
FROM ORG1.PATCHLINK_MACHINE_STATUS PMS
JOIN KBSYS.PATCHLINK_PATCH P on P.UID = PMS.PATCHUID 
JOIN MACHINE M on M.ID = PMS.MACHINE_ID
WHERE PMS.STATUS = "NOTPATCHED"
and P.TITLE LIKE "%KB3063858%"
