SELECT * FROM 
(SELECT MACHINE.NAME, MACHINE.CS_MANUFACTURER,
A.NAME as "Serial Number", AD.FIELD_32 as PONumber, AD.FIELD_10013 as POCreated,

group_concat(distinct LABEL.NAME separator ",") AS LABELS,
group_concat(distinct PARENTLABEL.NAME separator ",") AS PARENTLABELS
FROM ORG1.MACHINE
LEFT JOIN MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID)  
LEFT JOIN LABEL ON (LABEL.ID = MACHINE_LABEL_JT.LABEL_ID  AND LABEL.TYPE <> 'hidden')
LEFT JOIN LABEL_LABEL_JT on LABEL_LABEL_JT.CHILD_LABEL_ID = LABEL.ID
LEFT JOIN LABEL PARENTLABEL on (PARENTLABEL.ID = LABEL_LABEL_JT.LABEL_ID AND LABEL.TYPE <> 'hidden')
JOIN ASSET A on A.MAPPED_ID = MACHINE.ID
JOIN ASSET_DATA_5 AD on AD.ID = A.ASSET_DATA_ID
GROUP BY MACHINE.ID) as MACHINESWITHLABELS
WHERE PARENTLABELS not like '%Upgrade Status%'
and POCreated is null
ORDER BY NAME