SELECT DISTINCT(MACHINE.NAME), MACHINE.OS_NAME, MACHINE.CS_MODEL, MACHINE.CS_MANUFACTURER,
CASE 
    WHEN MACHINE.OS_NAME like 'Mac%' THEN MACADMINS.STR_FIELD_VALUE
    WHEN MACHINE.OS_NAME like '%Win%' THEN REPLACE(SUBSTRING_INDEX(SUBSTRING_INDEX(WINADMINS.STR_FIELD_VALUE, "-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -<br/>", -1), "<br/>The command completed successfully.", 1), "<br/>", ",")
END AS ADMINS
FROM MACHINE
LEFT JOIN MACHINE_CUSTOM_INVENTORY MACADMINS on MACHINE.ID = MACADMINS.ID and MACADMINS.SOFTWARE_ID = 59661
LEFT JOIN MACHINE_CUSTOM_INVENTORY WINADMINS on MACHINE.ID = WINADMINS.ID and WINADMINS.SOFTWARE_ID = 22066


ORDER BY MACHINE.NAME