SELECT 
LABEL.NAME as LOCATION, COUNT(M.ID)
FROM MACHINE M
LEFT JOIN MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = M.ID)  
LEFT JOIN LABEL ON (LABEL.ID = MACHINE_LABEL_JT.LABEL_ID  AND LABEL.TYPE <> 'hidden') 
LEFT JOIN LABEL_LABEL_JT ON (LABEL.ID = LABEL_LABEL_JT.CHILD_LABEL_ID AND LABEL_LABEL_JT.LABEL_ID = 439)

WHERE LABEL_LABEL_JT.LABEL_ID = 439 and
INET_ATON(M.IP) between INET_ATON("172.16.24.1") and INET_ATON("172.16.39.255")
GROUP BY LOCATION
ORDER BY LOCATION
