SELECT S.ID, S.DISPLAY_NAME, S.DISPLAY_VERSION, COUNT(MACHINE_SOFTWARE_JT.MACHINE_ID)
FROM ORG1.SOFTWARE S
JOIN MACHINE_SOFTWARE_JT on MACHINE_SOFTWARE_JT.SOFTWARE_ID = S.ID
WHERE DISPLAY_NAME like "Google Chrome"
GROUP BY S.DISPLAY_VERSION
ORDER BY S.DISPLAY_VERSION