--Good example of the CASE and SUM functions
--Count of computers based on their VLAN using INET_ATON function
--Computers grouped by their location label 
SELECT
LABEL.NAME as LOCATION, COUNT(M.ID) AS Total,
SUM(CASE WHEN INET_ATON(M.IP) between INET_ATON("172.16.16.1") and INET_ATON("172.16.23.255") then 1 else 0 end) as PubLab,
SUM(CASE WHEN INET_ATON(M.IP) between INET_ATON("172.16.24.1") and INET_ATON("172.16.31.255") then 1 else 0 end) as Acad,
SUM(CASE WHEN INET_ATON(M.IP) between INET_ATON("172.16.31.1") and INET_ATON("172.16.39.255") then 1 else 0 end) as Admin

FROM MACHINE M
LEFT JOIN MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = M.ID)
LEFT JOIN LABEL ON (LABEL.ID = MACHINE_LABEL_JT.LABEL_ID  AND LABEL.TYPE <> 'hidden')
LEFT JOIN LABEL_LABEL_JT ON (LABEL.ID = LABEL_LABEL_JT.CHILD_LABEL_ID AND LABEL_LABEL_JT.LABEL_ID = 439)

WHERE LABEL_LABEL_JT.LABEL_ID = 439
GROUP BY LOCATION
ORDER BY LOCATION
