SELECT concat(YEAR(CREATED), "/", LPAD(MONTH(CREATED), 2, "0")) as "Month", COUNT(TICKETS.ID) as "Count"
from (SELECT T.ID, T.TITLE, T.RESOLUTION,
GROUP_CONCAT(C.COMMENT) as COMMENTS,
CREATED
FROM ORG1.HD_TICKET T
JOIN HD_TICKET_CHANGE C on C.ID = T.ID
GROUP BY T.ID
HAVING COMMENTS REGEXP 'malware|virus|combofix|mbam|ccleaner'
or T.RESOLUTION REGEXP 'malware|virus|combofix|mbam|ccleaner'
or T.TITLE REGEXP 'malware|virus|combofix|mbam|ccleaner'
) as TICKETS
GROUP BY YEAR(CREATED), MONTH(CREATED)
ORDER BY YEAR(CREATED), MONTH(CREATED)
