select DATE(DATE_ADD(MAKEDATE(YEAR(CREATED), 1), INTERVAL WEEK(CREATED) WEEK) -2) as 'Week beginning', COUNT(HD_TICKET.CREATED)
from HD_TICKET
Where HD_TICKET.CREATED between '2013-07-07' AND '2013-08-03'
GROUP BY week(HD_TICKET.CREATED)


