-- Uses changes in employee description to find changes in status from active to inactive
-- lists assets that were assigned to those users 
SELECT USER.FULL_NAME as "Employee", OH.VALUE2 as "Description",  GROUP_CONCAT(ASSET.NAME) as "Assets",
GROUP_CONCAT(CASE
	WHEN ASSET.ASSET_TYPE_ID = 5 THEN M.NAME
    WHEN ASSET.ASSET_TYPE_ID = 8 THEN concat(PRINTER.FIELD_19, " ", PRINTER.FIELD_20)
END) as "Devices",
GROUP_CONCAT(DISTINCT(LOCATION_DATA.FIELD_40)) as "Liaison"
FROM ORG1.OBJECT_HISTORY OH
LEFT JOIN ASSET on ASSET.OWNER_ID = OH.OBJECT_ID
LEFT JOIN MACHINE M on M.ID = ASSET.MAPPED_ID
LEFT JOIN USER on USER.ID = OH.OBJECT_ID
LEFT JOIN ASSET LOCATION on LOCATION.ID = ASSET.LOCATION_ID
LEFT JOIN ASSET_DATA_1 LOCATION_DATA on LOCATION_DATA.ID = LOCATION.ASSET_DATA_ID
LEFT JOIN ASSET_DATA_8 PRINTER on PRINTER.ID = ASSET.ASSET_DATA_ID
WHERE OH.TYPE_NAME = "USER"
AND OH.FIELD_NAME = "CUSTOM_3"
AND OH.VALUE2 LIKE "%EMP_INACT%"
and OH.VALUE1 LIKE "%EMP_ACT%"
AND DATE(OH.TIME) > DATE_SUB(NOW(), INTERVAL 1 MONTH)
GROUP BY OH.OBJECT_ID
ORDER BY OH.TIME
