SELECT MACHINE.NAME,
       MACHINE.IP,
	   MACHINE.USER, 
       NTSERVICE.ID,
       NTSERVICE.STATUS,
       NTSERVICE.STARTUP_TYPE, 
       NTSERVICE.DISPLAY_NAME,
       MACHINE.MAC
  FROM (ORG1.MACHINE_NTSERVICE_JT MACHINE_NTSERVICE_JT
        INNER JOIN ORG1.NTSERVICE NTSERVICE
           ON (MACHINE_NTSERVICE_JT.NTSERVICE_ID = NTSERVICE.ID))
       INNER JOIN ORG1.MACHINE MACHINE
          ON (MACHINE_NTSERVICE_JT.MACHINE_ID = MACHINE.ID)
 WHERE (    NTSERVICE.STARTUP_TYPE = 'SERVICE_DISABLED' 
        AND NTSERVICE.DISPLAY_NAME = 'Intel(R) Management and Security Application Local Management Service')