SELECT LABEL.ID, LABEL.NAME, LABEL.NOTES, ASSET.* FROM LABEL
LEFT JOIN LABEL_LABEL_JT ON (LABEL.ID = LABEL_LABEL_JT.CHILD_LABEL_ID AND LABEL_LABEL_JT.LABEL_ID = 439)
LEFT JOIN ASSET on LABEL.NAME = ASSET.NAME
LEFT JOIN ASSET_DATA_1 ON ASSET_DATA_1.ID = ASSET.ASSET_DATA_ID
WHERE LABEL_LABEL_JT.LABEL_ID = 439
GROUP BY LABEL.ID