SELECT SOFTWARE.DISPLAY_NAME, MI.NOTES, MI_ATTEMPT.ATTEMPT_COUNT, MACHINE.NAME
FROM MI
JOIN MI_LABEL_JT on MI_LABEL_JT.MI_ID = MI.ID
JOIN MI_ATTEMPT on MI_ATTEMPT.MI_ID = MI.ID
JOIN MACHINE on MACHINE.ID = MI_ATTEMPT.MACHINE_ID
JOIN SOFTWARE ON SOFTWARE.ID = MI.SOFTWARE_ID
WHERE MI.ID = 349


