SELECT S.DESCRIPTION, GROUP_CONCAT(P.TITLE)
FROM ORG1.PATCHLINK_SCHEDULE S
JOIN ORG1.PATCHLINK_SCHEDULE_DEPLOY_LABEL_JT on ORG1.PATCHLINK_SCHEDULE_DEPLOY_LABEL_JT.PATCHLINK_SCHEDULE_ID = S.ID
JOIN ORG1.PATCHLINK_PATCH_LABEL_JT on ORG1.PATCHLINK_PATCH_LABEL_JT.LABEL_ID = ORG1.PATCHLINK_SCHEDULE_DEPLOY_LABEL_JT.LABEL_ID
JOIN KBSYS.PATCHLINK_PATCH P on P.UID = ORG1.PATCHLINK_PATCH_LABEL_JT.PATCHUID
WHERE P.IS_SUPERCEDED = 0
GROUP BY S.ID
