-- Report of computers in a patching schedule, their status and when patching ran
-- posted as part of answer to https://www.itninja.com/question/kace-reports-for-listing-machines-in-patch-schedule
-- Credit for initial query to https://www.itninja.com/user/Ziggi


SELECT MACHINE.NAME, PATCHLINK_SCHEDULE_RUN_MACHINE.STATUS,
PATCHLINK_SCHEDULE_RUN.LAST_UPDATED, PATCHLINK_SCHEDULE_RUN.RUN_TIME
FROM PATCHLINK_SCHEDULE_RUN_MACHINE 
JOIN MACHINE ON PATCHLINK_SCHEDULE_RUN_MACHINE.MACHINE_ID = MACHINE.ID 
JOIN PATCHLINK_SCHEDULE on PATCHLINK_SCHEDULE.ID = PATCHLINK_SCHEDULE_RUN_MACHINE.PATCHLINK_SCHEDULE_ID
JOIN PATCHLINK_SCHEDULE_RUN on PATCHLINK_SCHEDULE_RUN.ID = (SELECT MAX(PATCHLINK_SCHEDULE_RUN_ID) 
FROM PATCHLINK_SCHEDULE_RUN_MACHINE
WHERE PATCHLINK_SCHEDULE_ID = PATCHLINK_SCHEDULE.ID)
WHERE PATCHLINK_SCHEDULE.DESCRIPTION = "Patch Production Deploy"
and PATCHLINK_SCHEDULE_RUN_MACHINE.PATCHLINK_SCHEDULE_RUN_ID = 
(SELECT MAX(PATCHLINK_SCHEDULE_RUN_ID) 
FROM PATCHLINK_SCHEDULE_RUN_MACHINE
WHERE PATCHLINK_SCHEDULE_ID = PATCHLINK_SCHEDULE.ID)
ORDER BY MACHINE.NAME
