SELECT MACHINE.NAME, MACHINE.OS_NAME, PATCHED, NOTPATCHED, DETECT_FAILURES, LAST_RUN,
PATCHLINK_SCHEDULE_RUN_MACHINE.STATUS,
PATCHLINK_SCHEDULE_RUN.RUN_TIME,
PATCHLINK_SCHEDULE_RUN.LAST_UPDATED
FROM PATCHLINK_SCHEDULE_MACHINE_STATUS
JOIN MACHINE on MACHINE.ID = PATCHLINK_SCHEDULE_MACHINE_STATUS.MACHINE_ID
JOIN PATCHLINK_SCHEDULE_RUN_MACHINE ON PATCHLINK_SCHEDULE_RUN_MACHINE.MACHINE_ID = MACHINE.ID and PATCHLINK_SCHEDULE_RUN_MACHINE.PATCHLINK_SCHEDULE_ID = 32
JOIN PATCHLINK_SCHEDULE_RUN on PATCHLINK_SCHEDULE_RUN.ID = PATCHLINK_SCHEDULE_RUN_MACHINE.PATCHLINK_SCHEDULE_RUN_ID
WHERE PATCHLINK_SCHEDULE_MACHINE_STATUS.PATCHLINK_SCHEDULE_ID = 32
and PATCHLINK_SCHEDULE_RUN_MACHINE.PATCHLINK_SCHEDULE_RUN_ID = (SELECT MAX(PATCHLINK_SCHEDULE_RUN_ID) FROM PATCHLINK_SCHEDULE_RUN_MACHINE WHERE PATCHLINK_SCHEDULE_ID = 32)
and MACHINE.OS_NAME like "%Windows%"
ORDER BY STATUS, MACHINE.NAME