SELECT TITLE, VENDOR, IMPACTID, PATCHLINK_PATCH_STATUS.STATUS, COUNT(MACHINE_ID) AS INSTALLED
FROM KBSYS.PATCHLINK_PATCH
LEFT JOIN ORG1.PATCHLINK_MACHINE_STATUS on PATCHLINK_MACHINE_STATUS.PATCHUID = PATCHLINK_PATCH.UID
JOIN ORG1.PATCHLINK_PATCH_STATUS on ORG1.PATCHLINK_PATCH_STATUS.PATCHUID = PATCHLINK_PATCH.UID
WHERE ORG1.PATCHLINK_PATCH_STATUS.STATUS = 0
AND PATCHLINK_PATCH_STATUS.IS_SUPERCEDED = 0
GROUP BY UID
HAVING INSTALLED = 0 
ORDER BY IMPACTID, VENDOR, TITLE


