SELECT PMS.STATUS_DT, M.NAME, PMS.STATUS, P.TITLE 
FROM ORG1.PATCHLINK_MACHINE_STATUS PMS
JOIN KBSYS.PATCHLINK_PATCH P on P.UID = PMS.PATCHUID
JOIN MACHINE M on M.ID = PMS.MACHINE_ID
WHERE P.TITLE like "%KB3114717%"
