SELECT K.STARTED, K.COMPLETED, K.TYPE, M.NAME, PS.DESCRIPTION
FROM KBSYS.KONDUCTOR_TASK K 
JOIN ORG1.MACHINE M on M.KUID = K.KUID
JOIN ORG1.PATCHLINK_SCHEDULE PS on PS.ID = REPLACE(K.TYPE, "patch-ORG1-", '')
WHERE PHASE = "error"
and TYPE like 'patch%';