SELECT SOFTWARE.DISPLAY_NAME, SOFTWARE.PUBLISHER FROM ORG1.SOFTWARE 
JOIN MACHINE_SOFTWARE_JT on MACHINE_SOFTWARE_JT.SOFTWARE_ID = SOFTWARE.ID
JOIN MACHINE on MACHINE.ID = MACHINE_SOFTWARE_JT.MACHINE_ID
WHERE IS_PATCH = 1
and MACHINE.NAME = "steelc-nb"