SELECT DISTINCT P.ID, DESCRIPTION AS Description, 
P.LAST_RUN AS 'Last Run' , 
K.PHASE AS Phase , 
M.NAME AS Machine, 
M.ID as Machine_ID , 
PSMS.PATCHED, 
PSMS.NOTPATCHED
FROM PATCHLINK_SCHEDULE P 
LEFT JOIN KBSYS.KONDUCTOR_TASK K ON P.KONDUCTOR_TASK_TYPE = K.TYPE 
LEFT JOIN MACHINE M ON K.KUID = M.KUID 
LEFT JOIN PATCHLINK_SCHEDULE_MACHINE_STATUS PSMS ON PSMS.MACHINE_ID = M.ID
WHERE P.LAST_RUN <> 0 
AND DESCRIPTION not like '%Detect'ORDER BY M.NAME