SELECT PP.TITLE AS DISPLAY_NAME
     , SUM(if(MS.STATUS = 'PATCHED', 1, 0)) AS 'Patched'
, SUM(if(MS.STATUS = 'NOTPATCHED', 1, 0)) AS 'Not Patched'
, PP.RELEASEDATE
FROM
  ORG1.PATCHLINK_MACHINE_STATUS MS
INNER JOIN KBSYS.PATCHLINK_PATCH PP
ON PP.UID = MS.PATCHUID
INNER JOIN ORG1.MACHINE M
ON M.ID = MS.MACHINE_ID
INNER JOIN ORG1.PATCHLINK_PATCH_LABEL_JT
ON PATCHLINK_PATCH_LABEL_JT.PATCHUID = PP.UID
INNER JOIN ORG1.LABEL
ON PATCHLINK_PATCH_LABEL_JT.LABEL_ID = LABEL.ID
WHERE
  PP.RELEASEDATE between '2014-07-01' and '2014-08-31'
  AND LABEL.NAME = 'Adobe Patches'
  AND CS_DOMAIN = 'FAS.LCL'
GROUP BY
  DISPLAY_NAME
ORDER BY
  DISPLAY_NAME, PP.RELEASEDATE
