SELECT KBSYS.PATCHLINK_PATCH.TITLE,ORG1.PATCHLINK_MACHINE_STATUS.PATCHUID,
ORG1.PATCHLINK_MACHINE_STATUS.STATUS_DT, 
KBSYS.PATCHLINK_PATCH.FILENAME
FROM ORG1.PATCHLINK_MACHINE_STATUS 
JOIN KBSYS.PATCHLINK_PATCH on KBSYS.PATCHLINK_PATCH.UID = ORG1.PATCHLINK_MACHINE_STATUS.PATCHUID 
JOIN ORG1.MACHINE on MACHINE.ID = ORG1.PATCHLINK_MACHINE_STATUS.MACHINE_ID 
WHERE MACHINE.NAME = 'brindeal'
             and ORG1.PATCHLINK_MACHINE_STATUS.STATUS = 'NOTPATCHED';