SELECT MACHINE.NAME, PATCHED, NOTPATCHED, DETECT_FAILURES, 
PATCHLINK_SCHEDULE.DESCRIPTION, PATCHLINK_SCHEDULE_MACHINE_STATUS.LAST_RUN
FROM PATCHLINK_SCHEDULE_MACHINE_STATUS
JOIN MACHINE on MACHINE.ID = PATCHLINK_SCHEDULE_MACHINE_STATUS.MACHINE_ID
JOIN PATCHLINK_SCHEDULE on PATCHLINK_SCHEDULE.ID = PATCHLINK_SCHEDULE_MACHINE_STATUS.PATCHLINK_SCHEDULE_ID
WHERE PATCHLINK_SCHEDULE_ID = 1
AND NOTPATCHED > 0
ORDER BY NOTPATCHED DESC