SELECT PMS.STATUS_DT, M.NAME, PMS.STATUS, P.TITLE 
FROM KBSYS.PATCHLINK_PATCH P
LEFT JOIN ORG1.PATCHLINK_MACHINE_STATUS PMS on P.UID = PMS.PATCHUID
LEFT JOIN MACHINE M on M.ID = PMS.MACHINE_ID
WHERE P.TITLE like "%KB2760344%"