SELECT DESCRIPTION, LAST_RUN,
PENDING, DOWNLOADING, EXECUTING, 
REBOOTING, PAUSED, SUCCEEDED, 
FAILED, COMPLETED, OFFLINE 
FROM ORG1.PATCHLINK_SCHEDULE_RUN_COUNTS
JOIN PATCHLINK_SCHEDULE on PATCHLINK_SCHEDULE.ID = PATCHLINK_SCHEDULE_RUN_COUNTS.PATCHLINK_SCHEDULE_ID
WHERE PATCHLINK_SCHEDULE.DESCRIPTION = "Patch Production Deploy"
and PATCHLINK_SCHEDULE_RUN_COUNTS.ID = 
(SELECT MAX(PATCHLINK_SCHEDULE_RUN_ID) 
FROM PATCHLINK_SCHEDULE_RUN_COUNTS 
WHERE PATCHLINK_SCHEDULE_ID = PATCHLINK_SCHEDULE.ID)
