SELECT PMS.STATUS_DT, M.NAME, M.OS_NAME, M.USER,
LABEL.NAME as "Patching Schedule", 
PMS.STATUS, P.TITLE
FROM ORG1.PATCHLINK_MACHINE_STATUS PMS
JOIN KBSYS.PATCHLINK_PATCH P on P.UID = PMS.PATCHUID
JOIN MACHINE M on M.ID = PMS.MACHINE_ID
LEFT JOIN MACHINE_LABEL_JT ON (MACHINE_LABEL_JT.MACHINE_ID = M.ID)  
LEFT JOIN LABEL ON (LABEL.ID = MACHINE_LABEL_JT.LABEL_ID  AND LABEL.TYPE <> 'hidden') 
LEFT JOIN LABEL_LABEL_JT ON (LABEL.ID = LABEL_LABEL_JT.CHILD_LABEL_ID AND LABEL_LABEL_JT.LABEL_ID = 269)
WHERE (P.TITLE like "%4012212%"
or P.TITLE like "%4012215%"
or P.TITLE like "%4012606%"
or P.TITLE like "%4013198%"
or P.TITLE like "%4013429%"
or P.TITLE like "%4019264%")
and STATUS = "NOTPATCHED"
and LABEL_LABEL_JT.LABEL_ID = 269
ORDER BY LABEL.NAME, M.NAME

