SELECT MACHINE.ID, MACHINE.NAME, SC.CLIENT_CONNECTED, PSMS.PATCHED, PSMS.NOTPATCHED, PSMS.LAST_RUN, K.PHASE
FROM PATCHLINK_SCHEDULE_MACHINE_STATUS PSMS
JOIN MACHINE on MACHINE.ID = PSMS.MACHINE_ID
JOIN PATCHLINK_SCHEDULE P on P.ID = PSMS.PATCHLINK_SCHEDULE_ID
JOIN KBSYS.KONDUCTOR_TASK K ON P.KONDUCTOR_TASK_TYPE = K.TYPE and K.KUID = MACHINE.KUID
JOIN MACHINE_LABEL_JT on MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID
JOIN LABEL on LABEL.ID = MACHINE_LABEL_JT.LABEL_ID
JOIN KBSYS.SMMP_CONNECTION SC on SC.KUID = MACHINE.KUID
WHERE 
LABEL.NAME = "SL-Patch Production"
and K.TYPE = "patch-ORG1-3"
ORDER BY MACHINE.NAME
