SELECT KBOT.ID, KBOT.NAME, KBOT.MODIFIED, MAX(LOG.TIMESTAMP) as "Latest Start",
CONCAT_WS(" ", CRON.MINUTES, CRON.HOURS, CRON.DAYS_OF_MONTH, CRON.MONTHS, CRON.DAYS_OF_WEEK) as "Cron Schedule",
GROUP_CONCAT(MACHINE.NAME) as "Machines"
FROM KBOT
LEFT JOIN KBOT_LOG_LATEST LOG on LOG.KBOT_ID = KBOT.ID 
LEFT JOIN KBOT_CRON_SCHEDULE CRON on CRON.KBOT_ID = KBOT.ID
LEFT JOIN MACHINE on MACHINE.ID = LOG.MACHINE_ID
GROUP BY KBOT.ID