SELECT KBOT_LOG.STATUS, MACHINE.NAME, KBOT_LOG.START_TIME, KBOT_LOG_DETAIL.TEXT FROM ORG1.KBOT_LOG 
JOIN KBOT_LOG_DETAIL on KBOT_LOG_DETAIL.ID = OUTPUT_DETAIL_ID
JOIN MACHINE on MACHINE.ID = MACHINE_ID
WHERE KBOT_ID = 1197
