SELECT KBOT_LOG.ID, KBOT_LOG.START_TIME, MACHINE.NAME, KBOT.NAME, KBOT.ID, KBOT_LOG_DETAIL.TEXT, KBOT_CRON_SCHEDULE.*
FROM ORG1.KBOT_LOG
JOIN MACHINE on KBOT_LOG.MACHINE_ID = MACHINE.ID
JOIN KBOT on KBOT_LOG.KBOT_ID = KBOT.ID
JOIN KBOT_CRON_SCHEDULE on KBOT_LOG.KBOT_ID = KBOT_CRON_SCHEDULE.KBOT_ID
JOIN KBOT_LOG_DETAIL on KBOT_LOG_DETAIL.ID = KBOT_LOG.OUTPUT_DETAIL_ID
WHERE KBOT.ID = 581