SELECT KBOT.NAME, 
CASE 
    when KBOT.IM_CRON_ID = 0 then concat(KBOT_CRON_SCHEDULE.MINUTES," ", KBOT_CRON_SCHEDULE.HOURS," ", KBOT_CRON_SCHEDULE.DAYS_OF_MONTH," ", KBOT_CRON_SCHEDULE.MONTHS," ", KBOT_CRON_SCHEDULE.DAYS_OF_WEEK)
    else concat(IM_CRON.MINUTES," ", IM_CRON.HOURS," ", IM_CRON.DAYS_OF_MONTH," ", IM_CRON.MONTHS," ", IM_CRON.DAYS_OF_WEEK," ")

end as CRON,
CASE 
    when KBOT.IM_CRON_ID = 0 then "KBOT_CRON_SCHEDULE"
    else "IM_CRON"

end as CRONTYPE 

FROM ORG1.KBOT
LEFT JOIN KBOT_CRON_SCHEDULE on KBOT_CRON_SCHEDULE.KBOT_ID = KBOT.ID
LEFT JOIN IM_CRON on IM_CRON.ID = KBOT.IM_CRON_ID
HAVING CRON like "%"
ORDER BY KBOT.NAME