SELECT DISPLAY_NAME, DISPLAY_VERSION FROM ORG1.SOFTWARE
JOIN MACHINE_SOFTWARE_JT on MACHINE_SOFTWARE_JT.SOFTWARE_ID = SOFTWARE.ID
JOIN MACHINE on MACHINE.ID = MACHINE_SOFTWARE_JT.MACHINE_ID
WHERE MACHINE.NAME = "steelc"
ORDER BY DISPLAY_NAME
