SELECT 
  SOFTWARE.DISPLAY_NAME AS 'Software Display Name', 
  SOFTWARE.DISPLAY_VERSION AS 'Version', 
  KBOT.NAME AS 'Script Name',
  PORTAL.CREATED AS 'Creatione Date', 
  PORTAL.MODIFIED AS 'Modify Date', 
  PORTAL.ENABLED, 
  PORTAL.RESTRICT_MACHINE, 
  PORTAL.NOTES,
  PORTAL.ID,
  LABEL.NAME AS 'Label'
FROM   PORTAL
       LEFT JOIN SOFTWARE 
        ON PORTAL.SOFTWARE_ID = SOFTWARE.ID
       LEFT JOIN KBOT 
        ON KBOT.ID = PORTAL.KBOT_ID
	   LEFT JOIN PORTAL_LABEL_JT
		ON PORTAL.ID = PORTAL_LABEL_JT.PORTAL_ID AND PORTAL_LABEL_JT.LABEL_ID <> 0
	   LEFT JOIN LABEL
        ON PORTAL_LABEL_JT.LABEL_ID = LABEL.ID 
WHERE TIMESTAMP(PORTAL.MODIFIED) >= SUBDATE(NOW(), INTERVAL 1 DAY)