SELECT HD_TICKET.ID, HD_TICKET.TITLE, 
SUBSTRING_INDEX(HD_TICKET_CHANGE.DESCRIPTION, ".", 1) AS "Transfered"
FROM ORG1.HD_TICKET
JOIN HD_TICKET_CHANGE on HD_TICKET_CHANGE.HD_TICKET_ID = HD_TICKET.ID
WHERE HD_TICKET_CHANGE.DESCRIPTION like "%Changed ticket Queue%"
and HD_TICKET.TIME_CLOSED > DATE_SUB(NOW(), INTERVAL 1 MONTH)
