-- Work hours performed per worker per ticket closed in the previous 30 days

select HD_TICKET.ID,
HD_TICKET.TITLE,
HD_TICKET.TIME_CLOSED as TIME_CLOSED,
HD_PRIORITY.NAME as PRIORITY, 
HD_CATEGORY.NAME as CATEGORY, 
HD_STATUS.NAME as STATUS,
MACHINE.NAME as MACHINE_NAME,
WORKER.FULL_NAME as 'WORKER',
SUBMITTER.FULL_NAME as SUBMITTER_NAME
,format(SUM(time_to_sec(timediff(W.stop, W.start)))/3600.0,2) as 'Hours Worked'
from HD_TICKET
left join HD_CATEGORY on HD_CATEGORY_ID = HD_CATEGORY.ID
left join HD_STATUS on HD_STATUS_ID = HD_STATUS.ID
left join HD_PRIORITY on HD_PRIORITY_ID = HD_PRIORITY.ID
left join MACHINE on HD_TICKET.MACHINE_ID = MACHINE.ID
left join HD_WORK W on W.HD_TICKET_ID = HD_TICKET.ID
left join USER WORKER on WORKER.ID = W.USER_ID
LEFT JOIN USER SUBMITTER on SUBMITTER.ID = HD_TICKET.SUBMITTER_ID
where HD_STATUS.STATE = 'closed' and HD_TICKET.TIME_CLOSED > DATE_SUB(NOW(), INTERVAL 7 DAY)
GROUP BY HD_TICKET.ID, W.USER_ID

order by HD_TICKET.ID, HD_PRIORITY.ORDINAL, HD_CATEGORY.ORDINAL, HD_STATUS.ORDINAL