SELECT ID, CREATED, TIME_CLOSED, TIMEDIFF(TIME_CLOSED, CREATED) as TIMEDIFF, TIME_TO_SEC(TIMEDIFF(TIME_CLOSED, CREATED)) as SECONDSOPEN 
FROM ORG1.HD_TICKET
WHERE TIME_TO_SEC(TIMEDIFF(TIME_CLOSED, CREATED)) < 172800
and (YEAR(CREATED) = 2013 and QUARTER(CREATED) = (QUARTER(NOW()) -1))
