SELECT T.ID, T.CREATED, T.TIME_CLOSED, OWNER.FULL_NAME as "Owner", 
CLOSED.TIMESTAMP, CLOSED.DESCRIPTION,
CLOSER.FULL_NAME as "Closer"
FROM ORG1.HD_TICKET T
LEFT JOIN HD_TICKET_CHANGE CLOSED ON CLOSED.HD_TICKET_ID = T.ID and CLOSED.DESCRIPTION like '%Changed ticket Status from%to "Closed"%'

LEFT JOIN USER OWNER ON OWNER.ID = T.OWNER_ID
LEFT JOIN USER CLOSER ON CLOSER.ID = CLOSED.USER_ID
WHERE T.TIME_CLOSED > DATE_SUB(NOW(), INTERVAL 7 DAY)
AND (CLOSER.USER_NAME = "steelc" or CLOSER.USER_NAME = "loppi")
