-- breakdown of tickets that have not been changed in four hours
-- grouped by queue and priority
SELECT HD_QUEUE.NAME, HD_PRIORITY.NAME, COUNT(T.ID)
FROM ORG1.HD_TICKET T
JOIN HD_TICKET_CHANGE LAST_CHANGE ON LAST_CHANGE.HD_TICKET_ID = T.ID
 and LAST_CHANGE.ID=(select MAX(ID) from HD_TICKET_CHANGE where HD_TICKET_CHANGE.HD_TICKET_ID = T.ID)
left join HD_STATUS on HD_STATUS_ID = HD_STATUS.ID
left join HD_PRIORITY on HD_PRIORITY.ID = T.HD_PRIORITY_ID
left join HD_QUEUE on T.HD_QUEUE_ID = HD_QUEUE.ID
WHERE 
HD_STATUS.STATE != "closed"
 and LAST_CHANGE.TIMESTAMP < NOW() - INTERVAL 4 HOUR
GROUP BY HD_PRIORITY.ID 
ORDER BY HD_QUEUE.NAME, HD_PRIORITY.NAME
