-- count of tickets opened in date ranges per queue
-- uses case statements to count tickets
-- submitted as answer for https://www.itninja.com/question/creating-a-report-with-multiple-day-intervals

SELECT HD_QUEUE.NAME,
SUM(CASE WHEN CREATED BETWEEN DATE_SUB(NOW(), INTERVAL 15 DAY) and NOW() THEN 1 ELSE 0 END) AS '0-15',
SUM(CASE WHEN CREATED BETWEEN DATE_SUB(NOW(), INTERVAL 30 DAY) and DATE_SUB(NOW(), INTERVAL 15 DAY) THEN 1 ELSE 0 END) AS '15-30',
SUM(CASE WHEN CREATED BETWEEN DATE_SUB(NOW(), INTERVAL 60 DAY) and DATE_SUB(NOW(), INTERVAL 30 DAY) THEN 1 ELSE 0 END) AS '30-60'

FROM ORG1.HD_QUEUE
JOIN HD_TICKET on HD_TICKET.HD_QUEUE_ID = HD_QUEUE.ID
WHERE HD_QUEUE.ID in (2,3,4,10,12)
and HD_TICKET.TIME_CLOSED = '0000-00-00 00:00:00'
GROUP BY HD_QUEUE.ID
ORDER BY HD_QUEUE.NAME