SELECT T.ID, T.TITLE, C.COMMENT, C.TIMESTAMP, U.USER_NAME 
FROM ORG1.HD_TICKET T
JOIN HD_TICKET_CHANGE C on C.HD_TICKET_ID = T.ID and C.ID = (select MAX(ID) from HD_TICKET_CHANGE where HD_TICKET_CHANGE.HD_TICKET_ID = T.ID and HD_TICKET_CHANGE.COMMENT != '')
JOIN USER U on U.ID = C.USER_ID 
WHERE T.HD_QUEUE_ID = 2
and T.TIME_CLOSED = "0000-00-00 00:00:00"

