SELECT 
T.TITLE, T.ID, Q.NAME, P.NAME, 
T.CREATED, 
C.TIMESTAMP as "Owner Changed", 
TIMEDIFF(C.TIMESTAMP, T.CREATED) as "Created to Owner", 
CA.TIMESTAMP as "Approval Changed",
TIMEDIFF(CA.TIMESTAMP, T.CREATED) as "Created to Approval",
TIMEDIFF(C.TIMESTAMP, CA.TIMESTAMP) as "Approval to Owner"
FROM HD_TICKET T
JOIN HD_TICKET_CHANGE C on C.HD_TICKET_ID = T.ID 
JOIN HD_TICKET_CHANGE CA on CA.HD_TICKET_ID = T.ID 
JOIN HD_TICKET_CHANGE_FIELD CF on CF.HD_TICKET_CHANGE_ID = C.ID AND CF.FIELD_CHANGED = "OWNER_ID" and CF.BEFORE_VALUE = 0
JOIN HD_TICKET_CHANGE_FIELD CFA on CFA.HD_TICKET_CHANGE_ID = CA.ID AND CFA.FIELD_CHANGED = "APPROVAL" and CFA.AFTER_VALUE = "approved"
JOIN HD_PRIORITY P on P.ID = T.HD_PRIORITY_ID
JOIN HD_QUEUE Q on Q.ID = T.HD_QUEUE_ID



