SELECT T.ID, T.TITLE, USER.USER_NAME, C.ID, C.TIMESTAMP, C.COMMENT, C.DESCRIPTION, CF.FIELD_CHANGED, CF.AFTER_VALUE
FROM ORG1.HD_TICKET T
JOIN HD_TICKET_CHANGE C on C.HD_TICKET_ID = T.ID
JOIN HD_TICKET_CHANGE_FIELD CF on CF.HD_TICKET_CHANGE_ID = C.ID
JOIN USER on USER.ID = C.USER_ID
WHERE T.ID = "62577"
 