SELECT HD_TICKET.ID, HD_TICKET.CREATED,
HD_TICKET_CHANGE.TIMESTAMP,
TIMEDIFF(HD_TICKET_CHANGE.TIMESTAMP, HD_TICKET.CREATED),
HD_TICKET_CHANGE.DESCRIPTION
FROM ORG1.HD_TICKET
JOIN HD_TICKET_CHANGE on HD_TICKET.ID = HD_TICKET_CHANGE.HD_TICKET_ID 
    and HD_TICKET_CHANGE.DESCRIPTION like 'Changed ticket status from "New"%'
WHERE TIME_TO_SEC(TIMEDIFF(HD_TICKET_CHANGE.TIMESTAMP, HD_TICKET.CREATED)) > 3600
and HD_TICKET.CREATED > NOW() - INTERVAL 30 DAY