SELECT T.ID, T.TITLE, T.CREATED, FIRST_CHANGE.TIMESTAMP, FIRST_CHANGE.DESCRIPTION, T.TIME_CLOSED, FIRST_CHANGE.USER_ID, USER.FULL_NAME
FROM ORG1.HD_TICKET T
JOIN HD_TICKET_CHANGE FIRST_CHANGE ON FIRST_CHANGE.HD_TICKET_ID = T.ID
 and FIRST_CHANGE.ID=(select MIN(ID) from HD_TICKET_CHANGE where HD_TICKET_CHANGE.HD_TICKET_ID = T.ID and HD_TICKET_CHANGE.USER_ID !=0 and HD_TICKET_CHANGE.DESCRIPTION not like "Ticket Created%")
left join HD_STATUS on HD_STATUS_ID = HD_STATUS.ID
LEFT JOIN USER on USER.ID = FIRST_CHANGE.USER_ID
WHERE 
TIME_TO_SEC(TIMEDIFF(FIRST_CHANGE.TIMESTAMP, T.CREATED)) > 14400
and DATE(T.CREATED) = DATE(NOW()) - INTERVAL 1 DAY