SELECT CF.*, C.TIMESTAMP, STATBEFORE.NAME, STATBEFORE.STATE, STATAFTER.NAME, STATAFTER.STATE
FROM ORG1.HD_TICKET_CHANGE_FIELD CF
JOIN HD_TICKET_CHANGE C on C.ID = CF.HD_TICKET_CHANGE_ID
JOIN HD_STATUS STATBEFORE on STATBEFORE.ID = CF.BEFORE_VALUE
JOIN HD_STATUS STATAFTER on STATAFTER.ID = CF.AFTER_VALUE
WHERE FIELD_CHANGED = "HD_STATUS_ID"