-- Count of tickets for all categories per month this year
-- https://www.itninja.com/question/report-showing-listing-all-available-categories-count-tickets-per-category-per-month-current-year
-- Author: Chuck Steel

SELECT HD_CATEGORY.NAME AS Category, 
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 1 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS January,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 2 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS February,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 3 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS March,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 4 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS April,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 5 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS May,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 6 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS June,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 7 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS July,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 8 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS August,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 9 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS September,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 10 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS October,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 11 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS November,
(SELECT COUNT(ID) FROM HD_TICKET where 
HD_CATEGORY_ID = HD_CATEGORY.ID 
and MONTH(HD_TICKET.CREATED) = 12 and YEAR(HD_TICKET.CREATED) = YEAR(NOW())) AS December


FROM HD_CATEGORY

ORDER BY HD_CATEGORY.NAME

