SELECT HD_QUEUE.NAME, L.NAME, group_concat(USER.USER_NAME) as "Owners", group_concat(USER_LABEL_JT.USER_ID) as "Owner IDs"
FROM HD_QUEUE
LEFT JOIN HD_QUEUE_OWNER_LABEL_JT on HD_QUEUE_OWNER_LABEL_JT.HD_QUEUE_ID = HD_QUEUE.ID
JOIN LABEL L on L.ID = HD_QUEUE_OWNER_LABEL_JT.LABEL_ID
JOIN USER_LABEL_JT on USER_LABEL_JT.LABEL_ID = L.ID
JOIN USER on USER.ID = USER_LABEL_JT.USER_ID
GROUP BY HD_QUEUE.NAME