SELECT  DISTINCT(USER_NAME), 
EMAIL, DATE(USER.CREATED),
FULL_NAME, 
LOCATION.NAME as "Location",
GROUP_CONCAT(DISTINCT(TITLE.FIELD_VALUE)) as "Title", 
GROUP_CONCAT(DISTINCT(STATUS.FIELD_VALUE)) as "Status", 
GROUP_CONCAT(DISTINCT(DEPARTMENT.FIELD_VALUE)) as "Department" 
FROM ORG1.USER
JOIN USER_FIELD_VALUE TITLE on TITLE.USER_ID = USER.ID and TITLE.FIELD_ID = 1
JOIN USER_FIELD_VALUE STATUS on STATUS.USER_ID = USER.ID and STATUS.FIELD_ID = 3
JOIN USER_FIELD_VALUE DEPARTMENT on DEPARTMENT.USER_ID = USER.ID and DEPARTMENT.FIELD_ID = 1
JOIN ASSET LOCATION on LOCATION.ID = USER.LOCATION_ID


WHERE EMAIL like "%@dickinson.edu"
and USER.CREATED > DATE_SUB(NOW(), INTERVAL 7 DAY)
GROUP BY USER_NAME
ORDER BY USER_NAME