-- Report of users considered knowledge workers
-- We define knowledge workers as that are faculty and employees with a computer assigned to them

SELECT USER.EMAIL, 
DESCRIPTION.FIELD_VALUE as 'Description'
FROM USER
LEFT JOIN USER_FIELD_VALUE DESCRIPTION on DESCRIPTION.USER_ID = USER.ID and FIELD_ID = 3
WHERE 
DESCRIPTION.FIELD_VALUE like '%EMP_ACTIVE_FACULTY%'
AND USER.EMAIL like "%dickinson.edu"
GROUP BY USER.USER_NAME

UNION DISTINCT
(SELECT USER.EMAIL, 
DESCRIPTION.FIELD_VALUE as 'Description'
FROM USER
LEFT JOIN USER_FIELD_VALUE DESCRIPTION on DESCRIPTION.USER_ID = USER.ID and FIELD_ID = 3
WHERE 
DESCRIPTION.FIELD_VALUE like '%EMP_ACTIVE%'
AND USER.EMAIL like "%dickinson.edu"
AND (SELECT COUNT(ID) FROM ASSET WHERE OWNER_ID = USER.ID and ASSET_TYPE_ID = 5) > 0
GROUP BY USER.USER_NAME)
ORDER BY EMAIL